apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-staging
  labels:
    ver: "2"
    app: bandicoot
    env: staging
spec:
  replicas: 1
  # selector 爲必須
  selector:
    matchLabels:
      ver: "2"
      app: bandicoot
      env: staging
  template:
    # 這邊的 label 也要符合上面的設定
    metadata:
      labels:
        ver: "2"
        app: bandicoot
        env: staging
    spec:
      containers:
        - name: kuard-amd64
          image: gcr.io/kuar-demo/kuard-amd64:green